name: Test & Lint

on: [push]

jobs:
  test-lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@main    

      - name: Setup node env âš™ï¸
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14

      - name: Install lerna â¬‡ï¸
        run: npm install --global lerna

      - name: Cache node_modules ğŸ“¦
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}    
          restore-keys: |
            ${{ runner.os }}-modules-   

      - name: Setup database ğŸ—„ï¸
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '13.0-alpine'
          postgresql db: 'psql'
          postgresql user: 'psql'
          postgresql password: 'psql'

      - name: Install dependencies ğŸ‘¨ğŸ»â€ğŸ’»
        run:  lerna bootstrap

      - name: Run compile ğŸ—
        run: lerna run compile

      - name: Run linter ğŸ‘€
        run: lerna run format

      - name: Run tests ğŸ§ª
        run: lerna run test

      - name: Create code coverage archive ğŸ—œï¸
        run: find ./packages -name coverage -o -name jest_html_reporters.html | xargs tar cvzf code_coverage.tar.gz

      - name: Archive code coverage results â¬†ï¸
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: code_coverage.tar.gz
          retention-days: 1

      - name: Create graph dependencies ğŸ“ˆ
        uses: lerdajs/lerna-graph-action@1.0.0
        with: 
          rootPath: .
          imagePath: graph-dependencies.png

      - name: Archive graph dependencies results â¬†ï¸
        uses: actions/upload-artifact@v2
        with:
          name: graph-dependencies
          path: graph-dependencies.png
          retention-days: 1

  Pushing-code-coverage:
    runs-on: ubuntu-latest
    needs: test-lint
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@main   
        with:
          ref: 'ghpage'
      
      - name: Download code coverage results â¬‡ï¸
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report


      - name: Unarchive code coverage ğŸ—œï¸
        run: tar xvzf code_coverage.tar.gz
      
      - name: Download graph dependencies results â¬‡ï¸
        uses: actions/download-artifact@v2
        with:
          name: graph-dependencies
          
      - name: Commit file â¬†ï¸
        uses: EndBug/add-and-commit@v7
        with:
          add: '["packages", "graph-dependencies.png"]'
          branch: 'ghpage'
          message: 'chore: update code coverage files'